### PR TITLE
[DO NOT MERGE] Add search functionality, similar to guides-app

### PR DESCRIPTION
**Pull request by amyrlam**
Resolves: https://github.com/ember-learn/deprecation-app/issues/94

### CODE REVIEW

**Comment by amyrlam** [comment]
i fixed the algolia thing, i had it in the wrong place in config/environment, ugh

@mansona tried to run https://github.com/ember-learn/guides-app/pull/50 locally with https://github.com/ember-learn/ember-styleguide/pull/41 but i think i've botched the local npm link (was trying to get the SHA from https://github.com/ember-learn/ember-styleguide/pull/41 in my package.json by running that branch locally) 

may just wait for the ember-styleguide PR to land on master then update the package.json try again

**Comment by mansona** [comment]
first of all 😍 this is **exactly** what I was hoping to see in this implementation 🎉 yay!!

as for the sha issues we're having, you can just replace the sha with a branch name for now and mark this as `[DO NOT MERGE]` so it works out of the box if anyone wants to test it i.e. replace `"ember-styleguide": "github:ember-learn/ember-styleguide#170e94742d310bd7cd28f1cb757c741816a58d16",` with `"ember-styleguide": "github:ember-learn/ember-styleguide#feature/external-search",` 👍

**Comment by amyrlam** [comment]
Sorry for the delay, been a slow one getting back into the post-conf groove. Totally my bad!

If I run https://github.com/ember-learn/guides-app/pull/50 locally but change the `package.json` to `"ember-styleguide": "github:ember-learn/ember-styleguide#feature/external-search-2"`, run a `npm install` ... this is what I'm getting ... no calls being made?

search-bar

Same running https://github.com/ember-learn/guides-app/pull/50 as-is.

Also I'm a little confused by the page service, will follow along on guides-app / ember-styleguide.

**Comment by mansona** [comment]
Hey @amyrlam 👋 now that we've ironed out all the issues on the Guides side this should be a bit easier 🎉 

You will see if you look at the guides now that I'm passing in https://github.com/ember-learn/ember-learn-search-components via yield to the header. If you can do the same it should start working!

Also, we can't re-create the page service on deprecations so just hard-code the version that is being passed into the search components to `v3.0.0` for now 👍

**Comment by amyrlam** [comment]
@mansona @toddjordan let's revisit this when we / me and Chris pair, will close 

I currently see search NOT working on https://guides.emberjs.com/release/ or https://emberjs.com/deprecations/ ... I saw it working on https://emberjs.com/api/ember/release a few days ago but not now?

**Pull request closed without merging**
