### PR TITLE
Deprecate Route.router

### PR DESCRIPTION
**Pull request by cibernox**
Replaces old PR to website: https://github.com/emberjs/website/pull/3211

### CODE REVIEW

**Comment by cibernox** [comment]
@rwjblue Something weird happened with the tests. They pass locally. Can you trigger a rebuild?

**Comment by rwjblue** [comment]
CI is failing, looks like it needs a newer ember-cli-qunit?

**Comment by cibernox** [comment]
That the first thing that I checked, but it's in qunit 4.3.2 already. I can only think that yarn had a stroke.

**Comment by rwjblue** [comment]
kk, hopefully (I restarted CI)

**Comment by cibernox** [comment]
@rwjblue Green now

**Pull request merged**
