### PR TITLE
chore: tidy up the deprecation titles

### LINKED ISSUE #783: Tidy up deprecation titles
Some deprecations include the word "Deprecation" or "Deprecation" in the title. This is superfluous since these are deprecation guides, so this could be tidied up.

An example:
Deprecation: https://deprecations.emberjs.com/v3.x#toc_ember-glimmer-with-syntax
Current title: Deprecate transition methods of routes and controllers 
Updated title: Transition methods of routes and controllers

### PR DESCRIPTION
**Pull request by Windvis**
- remove "Deprecate" everywhere
- wrap code with `backticks`
- wrap `{{helpers}}` in curlies
- wrap components in `<AngleBrackers>`

Closes #783

### CODE REVIEW

**Comment by Windvis** [comment]
@locks I also added some `backticks`, {{helpers}} and `<AngleBrackets>`. It looks like those aren't fully consistent at the moment. I only changed the ones that included Deprecate in the title though. If that is a wanted change I can go back and recheck the other files if you want.

**Comment by locks** [comment]
Thanks for the help and for also doing further normalization of the titles! Unfortunately backticks don't seem to do anything in titles, let me check with someone else in the learning team to see what we want going forward.

**Comment by locks** [comment]
Opened https://github.com/ember-learn/deprecation-app/issues/787 as a follow-up.

**Review by locks — APPROVED** [review]
Thanks for the help!

**Pull request merged**
