### PR TITLE
Remove erraneous Route#willTransition and Route#didTransition deprecation guidance

### LINKED ISSUE #253: Potential issue with code snippet for router events deprecation in Ember 3.6 section
Hi.  I'm sorry if this is not the right place to post this but I have been having a discussion with a few members of the community about this deprectaion:

https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_deprecate-router-events

In the deprecations guide there is a code example of how to replace the willTransition/didTransition hooks with routeWillChange/routeDidChange.  The example says that the new event listeners should be registered in the init() method but this results in the new events firing as you transition to AND away from a particular route. To mimic willTransition the routeWillChange event should only fire when transitioning away from the route. Likewise, in order to mimic didTransition the routeDidChange event should only fire as you enter a route. 

Another community member has suggested that the correct method that should be used to register the new listeners is activate() rather than init().  This does result in the correct behaviour where routeWillChange mimics willTransition etc.

How do we go about deciding if the code snippet should be modified? Do we need to contact the deprecation author for confirmation?

Thanks.

### PR DESCRIPTION
**Pull request by efx**
Fixes #253. See conversations in ember-dev-learning on discord:
https://discordapp.com/channels/480462759797063690/480777444203429888/536988540010102784

### CODE REVIEW

**Comment by efx** [comment]
[Rendered](https://github.com/efx/deprecation-app/blob/fix-253/content/ember/v3/router-events.md)

**Comment by rwjblue** [comment]
@chadhietala - Can you review?

**Comment by efx** [comment]
hold off on merging, I think there is some confusion around `willTransition` `didTransition` deprecations per route.

**Comment by efx** [comment]
Ok, per the discussion in discord ember-js-dev, I think this is the correct deprecation guidance.

**Pull request merged**
