### PR TITLE
Add (basic) deprecation guide for setting-on-hash

### LINKED ISSUE #1085: Document `setting-on-hash` deprecation
Motivation:
https://github.com/emberjs/ember.js/issues/19975

Location where the deprecation is triggered:
https://github.com/glimmerjs/glimmer-vm/blob/9c44e6835d27fcc7dc0e276cf3b0ee011d1ffb90/packages/%40glimmer/runtime/lib/helpers/hash.ts#L15-L21

### PR DESCRIPTION
**Pull request by shubham-y**
Added documentation for deprecation message with id "setting-on-hash"
Example: `DEPRECATION: You set the 'example' property on a {{hash}} object. Setting properties on objects generated by {{hash}} is deprecated. Please update to use an object created with a tracked property or getter, or with a custom helper. [deprecation id: setting-on-hash] `

Closes #1085 

Reference: https://github.com/emberjs/ember.js/blob/21b3733485ad364b5ac71c3423ab821b6e3ded4a/packages/%40ember/-internals/glimmer/lib/environment.ts#L115-L123

### CODE REVIEW

**Review by harshith-venkatesh — APPROVED** [review]

**Review by rohan09-raj — APPROVED** [review]

**Review by ankushdharkar — APPROVED** [review]
Nicely done @shubham-y. Thanks for adding this 👍

**Comment by shubham-y** [comment]
Made requested changes based on comments in dev-ember-learning on discord:
https://discord.com/channels/480462759797063690/966996682531287040/966997869653553192

**Review by locks — APPROVED** [review]
This looks good, thank you!

**Comment by locks** [comment]
Merging as we've run out of Percy snapshots again.

**Pull request merged**
