### PR TITLE
Make individual pages for deprecations

### PR DESCRIPTION
**Pull request by jenweber**
Closes https://github.com/ember-learn/deprecation-app/issues/1256

Goal:
URLS like like `https://deprecations.emberjs.com/id/some-deprecation` bring you to a guide about an individual deprecation

Progress so far:

Screen Shot 2023-01-29 at 4 13 45 PM

### CODE REVIEW

**Comment by jenweber** [comment]
@mansona this is ready for review. I updated the markup to account for having a single-deprecation page with one heading, and included a breadcrumb-style link. If this passes your click test, I think it is good to go.

I think we will need to give a little README guidance about how to figure out what the individual URL of a new deprecation will be. I would like to do that as a followup PR.

**Comment by jenweber** [comment]
cc @kategengler I think this is just about ready. URLs for individual deprecation pages will look something like `http://localhost:4200/id/blueprint.add-bower-packages-to-project`

**Comment by kategengler** [comment]
Excellent! 🥳

**Review by mansona — CHANGES_REQUESTED** [review]
- [x] remove ids from all markdowns
- [x] make sure the filenames matched all ids that were there
- [x] add a linter that prevents anyone adding id again

for example check filename `v4/auto-location.md` which has an ID of `deprecate-auto-location`

**Comment by kategengler** [comment]
Any chance this can merge?

**Comment by kategengler** [comment]
@jenweber Wondering if we can find someone to get this over the line? Hate for it to go stale.

**Comment by jenweber** [comment]
@kategengler Here's some info on where we're at and how it intersects with ember.js. Chris & I worked on this the past 2 Fridays and are getting close! We renamed files to match their ids, sorted out a file naming clash, and next up we will work on a linter for this repo to enforce the new pattern.

From a UX perspective - the pages that are in prod today will have no changes - anchor links and all that will work exactly the same. New individual page URLs will be derived from the `id` specified in the frontmatter. 

In ember.js, we would have a few options then for simplifying the experience. Here's one of them. We could write a private wrapper in ember source that generates the link based on the URL, and lint against including `url` in the deprecation options. That link would go to the individual deprecation page. These improvements do not block the launch of the deprecation app improvements, since everything is backwards compatible.

Let us know if you have any thoughts on how the url is done in emberjs.

**Comment by mansona** [comment]
@jenweber I think this is working now. I removed the scripts because they didn't seem useful to commit, but I preserved them in a new branch if we need to run them again https://github.com/ember-learn/deprecation-app/tree/jw-cm-script-for-fixing-content

**Review by mansona — APPROVED** [review]
woop woop!

**Pull request merged**
