### PR TITLE
jQuery be gone

### PR DESCRIPTION
**Pull request by jaredgalanis**
- removes jquery from dep-article component
- converts dep-article to class-based component
- turn off optional feature
~~- blow away node modules~~

### CODE REVIEW

**Comment by locks** [comment]
Love to see it!

**Comment by jaredgalanis** [comment]
> Love to see it!

yeah, have a few things to fix with the tests, but hopefully can wrap that up today.

**Comment by jaredgalanis** [comment]
> > Love to see it!
> 
> yeah, have a few things to fix with the tests, but hopefully can wrap that up today.

@locks should be ready now.

Closes #583

**Comment by locks** [comment]
Thanks for the help as always :)

**Pull request merged**
